/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dim.client.gui;

import com.dim.client.domain.Contact;
import com.dim.client.msg.ConnManager;
import com.dim.client.net.Client;
import io.netty.channel.ChannelOutboundHandlerAdapter;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.WindowConstants;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author daiyma
 */
public class WndTalk extends javax.swing.JFrame {

    private static final Logger logger = org.apache.logging.log4j.LogManager.getLogger(WndTalk.class);
    private Contact user = new Contact("我");
    private Contact contact;
    
    private Client conn;

    /**
     * Creates new form Message
     */
    public WndTalk() {
        super();
    }

    public WndTalk(Contact contact,Client conn) throws HeadlessException {

        super("与 " + contact.getDisplayName() + " 聊天中");

        this.contact = contact;
        //URL iconURL = getClass().getResource("/images/head.png");
        //ImageIcon icon = new ImageIcon(iconURL);
        //this.setIconImage(icon.getImage());

        this.setSize(480, 360);

        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        initComponents();

        txtaMsg.addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent arg0) {

                // 关键设置，当Ctrl+Enter组合键按下时响应   
                if ((arg0.getKeyCode() == KeyEvent.VK_ENTER)
                        && (arg0.isControlDown())) {
                    btnSendActionPerformed(null);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaScreen = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        btnFont = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnFace = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnShortcut = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnSendFile = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnHistory = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaMsg = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setLocationByPlatform(true);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setAutoscrolls(true);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setAutoscrolls(true);

        txtaScreen.setColumns(20);
        txtaScreen.setEditable(false);
        txtaScreen.setFont(new java.awt.Font("宋体", 0, 13)); // NOI18N
        txtaScreen.setRows(5);
        jScrollPane1.setViewportView(txtaScreen);

        jTabbedPane1.addTab("消息", jScrollPane1);

        jToolBar1.setFloatable(false);

        btnFont.setText("字体");
        btnFont.setToolTipText("字体");
        btnFont.setFocusable(false);
        btnFont.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFont.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFontActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFont);
        jToolBar1.add(jSeparator3);

        btnFace.setText("表情");
        btnFace.setToolTipText("表情");
        btnFace.setFocusable(false);
        btnFace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnFace);
        jToolBar1.add(jSeparator1);

        btnShortcut.setText("截图");
        btnShortcut.setToolTipText("截图");
        btnShortcut.setFocusable(false);
        btnShortcut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShortcut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnShortcut);
        jToolBar1.add(jSeparator2);

        btnSendFile.setText("传送文件");
        btnSendFile.setToolTipText("发送文件");
        btnSendFile.setFocusable(false);
        btnSendFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSendFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSendFile);
        jToolBar1.add(jSeparator4);

        btnHistory.setFocusable(false);
        btnHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistory.setLabel("消息记录");
        btnHistory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnHistory);

        btnSend.setLabel("发送");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnClose.setLabel("关闭");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtaMsg.setColumns(20);
        txtaMsg.setFont(new java.awt.Font("宋体", 0, 13)); // NOI18N
        txtaMsg.setLineWrap(true);
        txtaMsg.setRows(6);
        txtaMsg.setWrapStyleWord(true);
        txtaMsg.setAutoscrolls(false);
        jScrollPane3.setViewportView(txtaMsg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSend)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose)
                    .addComponent(btnSend))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        this.sendMessage();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFontActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

        //TODO 关闭socket 链接
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WndTalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WndTalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WndTalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WndTalk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WndTalk().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFace;
    private javax.swing.JButton btnFont;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendFile;
    private javax.swing.JButton btnShortcut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea txtaMsg;
    private javax.swing.JTextArea txtaScreen;
    // End of variables declaration//GEN-END:variables

    private class Talker extends Thread {

        Contact contact;

        public Talker(Contact ct) {
            contact = ct;
        }

        @Override
        public void run() {
            //TODO
            logger.info("和" + contact + "建立TCP连接，开始会话");
        }
    }

    public void talk() {
        new Talker(contact).start();
    }

    private void sendMessage() {
        SimpleDateFormat fmt = new SimpleDateFormat("hh:mm:ss");
        String msg = txtaMsg.getText();

        if (!org.apache.commons.lang3.StringUtils.isBlank(msg)) {
            txtaScreen.append(user.toString());
            txtaScreen.append(fmt.format(Calendar.getInstance().getTime()));
            txtaScreen.append(" ");
            txtaScreen.append(msg.trim());
            txtaScreen.append("\r\n");
            txtaMsg.setText(null);
            logger.info("sending throu socket~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
            
            ChannelOutboundHandlerAdapter writer = ConnManager.getMessageWriteHandler();
        }
    }
}
